name: 'Tobis Docker Image CI'
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["linux-transifex"]
    
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      name: Setup Docker BuildX system
    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: (github.ref == 'refs/heads/master') && (github.repository == 'FearlessTobi/build-environments')
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      name: Build image
      with:
        push: ${{ (github.ref == 'refs/heads/master') && (github.repository == 'FearlessTobi/build-environments') }}
        context: ${{ matrix.image }}
        tags: FearlessTobi/build-environments:${{ matrix.image }}
